# Generated by Django 3.2.3 on 2021-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Unit', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Mileage', models.CharField(max_length=200)),
                ('Manufacturer', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
