# Generated by Django 3.2.3 on 2021-06-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDistanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CumilativeDistance', models.IntegerField()),
                ('LogDate', models.DateField()),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleAPI.vehicle')),
            ],
            options={
                'unique_together': {('Unit', 'LogDate')},
            },
        ),
    ]
